version: '2.4'

services:
    backend:
        build: 
            context: .
            target: backend
        image: twilio:backend
        ports: 
            - '8080:8080'
    frontend:
        depends_on: 
            - backend
        build:
            context: .
            target: frontend
        image: twilio:frontend
        links: 
            - backend
        ports: 
            - '3000:3000'
    nginx: 
        depends_on: 
            - frontend
            - backend
        build:
            context: .
            target: reverseproxy
        image: twilio:reverseproxy
        links:
            - backend
            - frontend
        ports:
            - '7000:7000'
